version: "3.8"

volumes:
  postgres_data:

networks:
  backend:

services:
  app:
    container_name: seabasket-app
    image: seabasket
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    networks:
      - backend

  db:
    container_name: seabasket-db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  liquibase:
    container_name: seabasket-liquibase
    image: liquibase/liquibase:latest
    networks:
      - backend
    depends_on:
      - db
    volumes:
      - ./liquibase/changelog.xml:/liquibase/changelog.xml
      - ./liquibase/liquibase.properties:/liquibase/liquibase.properties
      - /home/vivek/liquibase-temp/:/liquibase/lib
    command: --defaults-file=/liquibase/liquibase.properties update
